### ISSUE TITLE
Contents of Server - Not responding after 5 minutes being used

### ISSUE THREAD

**Issue by Axort** [nkreipke/FTPManager#19]
Hi!

First of all, I think FTPManager is great! Keep up with the good work.

Here is my problem:
I download a list of directories from a location in our FTP server; everything works fine if you keep using the app. (reloading the list, for example). But if you leave the app open (and it doesn't go to background) and after 5 minutes or so you try reloading the list of directories, it never responds.

I did some debugging and found out that in FTPManager.m -> - (NSArray_) _contentsOfServer:(FMServer_)server the code never passes this line: CFRunLoopRun(); I don't know why it works fine the first time and if you keep using the app.

Here is my code:

``` Objective-C
-(void)list:(NSString *)directory
{
    [self performSelectorInBackground:@selector(listDirectory:) withObject:directory];
}

-(void)listDirectory:(NSString *)directory
{
    if(self.ftpManager)
        self.ftpManager = nil;

    self.ftpManager = [[FTPManager alloc] init];

    self.success = NO;
    NSArray *serverData = nil;
    FMServer *server = [FMServer serverWithDestination:[NSString stringWithFormat:@"[URL]/%@", directory] username:FTP_USERNAME password:FTP_PASSWORD];

    serverData = [self.ftpManager contentsOfServer:server];

    [self performSelectorOnMainThread:@selector(endList:) withObject:serverData waitUntilDone:NO];
}
```

Thanks in advance.

**Comment by haemi** [comment]
did you ever find a solution for this?

**Comment by Axort** [comment]
What I did was call the contentsOfServer method each minute so the connection to the ftp server remains active. I know this is not a solution but is a workaround. I did some research and found out that the client loses the connection to the ftp server after some time for security reasons. This is a characteristic of the file transfer protocol

**Comment by haemi** [comment]
I do get deadlocks with this solution, they're rare, but they occur. And if I use the ```checkLogin``` method, any currently running operation gets cancelled... I'm really stuck here :(

**Comment by acuenco** [comment]
I am getting the same issue. Once I leave the app open with an active FTP connection for about 5 minutes of inactivity, the app just crashes. Is there a way to timeout FMServer?
