### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by alex-v1981** [nkreipke/FTPManager#21]
We found many crashes on the line 208 (FTPManager.m). It's something to do with the UTF-8 encoding.
![2015-02-26 9 42 59](https://cloud.githubusercontent.com/assets/8733082/6407984/a51d7b8e-be5c-11e4-87e7-cc9f7559d4e9.png)

**Comment by nkreipke** [comment]
Anything helpful inside the logs? What's the value of nameEntry when the crash occurs?

**Comment by alex-v1981** [comment]
We do not know. Crash took out crashlytics.com

**Comment by alex-v1981** [comment]
2015-03-10 14:01:27.870 RManager[13064:731796] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** setObjectForKey: object cannot be nil (key: kCFFTPResourceName)'
First throw call stack:
(
0 CoreFoundation 0x000000010d7baa75 __exceptionPreprocess + 165
1 libobjc.A.dylib 0x000000010d453bb7 objc_exception_throw + 45
2 CoreFoundation 0x000000010d6c12e8 -[__NSDictionaryM setObject:forKey:] + 968
3 RManager 0x00000001071ecf59 -[FTPManager _createListingArrayFromDirectoryListingData:] + 665
4 RManager 0x00000001071eee73 -[FTPManager _contentsOfServer:] + 1907
5 RManager 0x00000001071f186e __31-[FTPManager contentsOfServer:]_block_invoke + 46
6 RManager 0x00000001071ec649 -[FMThread threadMain] + 73
7 Foundation 0x000000010a3cc1dd _NSThreadmain_ + 1194
8 libsystem_pthread.dylib 0x000000010e573268 _pthread_body + 131
9 libsystem_pthread.dylib 0x000000010e5731e5 _pthread_body + 0
10 libsystem_pthread.dylib 0x000000010e57141d thread_start + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Printing description of entry: { kCFFTPResourceGroup = allaccount; kCFFTPResourceLink = ""; kCFFTPResourceModDate = "2015-03-10 06:38:00 +0000"; kCFFTPResourceMode = 511; kCFFTPResourceName = "\U00ac\U00ce\U2021\U00d2\U00da\U00c2\U00ce\U00cb\U00cc \U00cd\U00d3\U00ce\U00c2\U02c6 - \U00a1\Uf8ff\U2021\U00da\U00d2\U00da\U201a\U00d3 \U00cd\U00d3\U00ce\U00b8\U02c6\U2021.(\U2013\U2021\U00d2\U00af\U00cb\Uf8ff\U00c2\U00cc\U00cc\U00d3\U00c2 \U00bb\U00c1\U2030\U2021\U00cc\U00cb\U00c2).(2001).2\U0192\U00cb\U00d2\U00cd\U2021.BDRip.720p.NLT"; kCFFTPResourceOwner = user; kCFFTPResourceSize = 4096; kCFFTPResourceType = 4; }
Printing description of nameEntry:
¬Î‡ÒÚÂÎËÌ ÍÓÎÂˆ - ¡‡ÚÒÚ‚Ó ÍÓÎ¸ˆ‡.(–‡Ò¯ËÂÌÌÓÂ »Á‰‡ÌËÂ).(2001).2ƒËÒÍ‡.BDRip.720p.NLT

**Comment by nkreipke** [comment]
Pretty weird. Tested it with the exact file name and it did not crash. Do you happen to know the FTP server used?

I'd recommend temporarily fixing it like this:
```
if ((nameEntry = entry[(id)kCFFTPResourceName])) {
    NSString *utf8Str = [[NSString alloc] initWithData:[nameEntry dataUsingEncoding:NSMacOSRomanStringEncoding allowLossyConversion:YES]
encoding:NSUTF8StringEncoding];
    if (utf8Str)
        entry[(id)kCFFTPResourceName] = utf8Str;
}
```

**Comment by alex-v1981** [comment]
For test try to use unicode string:

kCFFTPResourceName = "\U00ac\U00ce\U2021\U00d2\U00da\U00c2\U00ce\U00cb\U00cc \U00cd\U00d3\U00ce\U00c2\U02c6 - \U00a1\Uf8ff\U2021\U00da\U00d2\U00da\U201a\U00d3 \U00cd\U00d3\U00ce\U00b8\U02c6\U2021.(\U2013\U2021\U00d2\U00af\U00cb\Uf8ff\U00c2\U00cc\U00cc\U00d3\U00c2 \U00bb\U00c1\U2030\U2021\U00cc\U00cb\U00c2).(2001).2\U0192\U00cb\U00d2\U00cd\U2021.BDRip.720p.NLT"

> I'd recommend temporarily fixing it like this:
Could you apply these changes to your repository?
