### ISSUE TITLE
Cannot connect to FTP

### ISSUE THREAD

**Issue by bunkerbilly** [nkreipke/FTPManager#26]
Hi, 

i have set all the credentials needed for the FMServer ( Dest, port, user, pass ) but it fails to connect to the server ( the login credentials are correct ).

using your CheckLogin method in FTPManager it returns failed but the server tells me that it has connected properly.

when i run any other method the server tells me it has logged in successfully but then returns the error "site command failed"

when i run it through your example app i get the error - 2016-12-12 12:30:52.501137 FTPManager[57990:10784190] ftp stream failed: general stream error (check credentials?)

what am i doing wrong?

**Comment by nkreipke** [comment]
Hi,

could you set a breakpoint in FTPManager.m on line 789 and print the value of the variable ```a```? This way we could see what the server actually answers.

**Comment by bunkerbilly** [comment]
no longer using this library, thanks for your reply though.
