### ISSUE TITLE
Does not connect with FTP over explicit TLS/SSL

### ISSUE THREAD

**Issue by amitds** [nkreipke/FTPManager#27]
I am trying to connect with "ftp.onehub.com" FTP over explicit TLS/SSL but it always fails to connect and below log prints -

_FTPManager[9987:118563] ftp stream failed: general stream error (check credentials?)_

The login credentials are right because it connects with FireFTP, Connection type - Auth SSL or TSL.

Please help.

**Comment by nkreipke** [comment]
Unfortunately FTPManager does not support FTPS and likely never will as the underlying CFStream does not implement the necessary protocols. You may want to look into [libcurl](https://curl.haxx.se/libcurl/) for this.
